{% set name = "pyfastspm" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d76fbd1e72de40d3a2b8f817b82b3329cbaa1812407fae93df624f5e951a7d1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - packaging
    - matplotlib-base
    - h5py
    - scipy
    - numpy
    - pillow
    - tqdm
    - ffmpeg
    - mkl_fft
    - scikit-image
    - seaborn

test:
  imports:
    - pyfastspm
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://fastspm.gitlab.io/pyfastspm/
  license: MIT AND Apache-2.0
  license_file: LICENSE
  summary: A python package for loading, processing and exporting scanning probe microscopy movies acquired with the FAST unit.
  doc_url: http://fastspm.gitlab.io/pyfastspm/
  dev_url: https://gitlab.com/fastspm/pyfastspm/

extra:
  recipe-maintainers:
    - carlodri
    - mpanighel
